spring.application.name=2LLMs

# To disable ChatClient.Builder auto-config to write custom beans for both(2) LLMs
spring.ai.chat.client.enabled=false  
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-5-nano
spring.ai.openai.chat.options.temperature=1

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash


logging.level.root=INFO
