spring.security.oauth2.client:
  provider:
    twitter:
      authorization-uri: https://twitter.com/i/oauth2/authorize
      token-uri: https://api.twitter.com/2/oauth2/token
      user-info-uri: https://api.twitter.com/2/users/me
      user-name-attribute: id

  registration:
    google:
      client-id: 523286115429-47i2jg4k5l4lmreqbkdkr72pinlr4uta.apps.googleusercontent.com
      client-secret: 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
    github:
      client-id: Ov23lisOdxadn02W8aZo
      client-secret: 2fe41833af39ad72cff6ee13df99a36019b65e3b
    twitter:
      client-id: adsadsada
      client-secret: 4fvvsddsdfds
      redirect-uri: "{baseUrl}/login/oauth2/code/twitter"
      authorization-grant-type: authorization_code
      scope:
        - tweet.read
        - users.read
        - offline.access
      client-name: Twitter